[package]
authors = ["deciduously <ben@deciduously.com>"]
edition = "2018"
name = "hunt-the-wumpus"
version = "1.0.1"
[[bin]]
name = "hunt"
path = "src/main.rs"

[dependencies]
stdweb = "0.4"
yew = "0.7"

[lib]
name = "hunt_the_wumpus"
path = "src/lib.rs"
